version: '3.8'

services:
  nezha-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${USERNAME}/nezha-telegram-bot:latest
    container_name: nezha-telegram-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: unless-stopped